remote_theme: "jeffreytse/jekyll-theme-yat"
plugins:
  - jekyll-remote-theme

lsi: false
safe: true
source: jennagreenwood8.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge